name: Update Journals Function

on:
  schedule:
    - cron: "0 * * * *"   # تشغيل كل ساعة عند الدقيقة 0
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t update-journals .

      - name: Verify Node.js version and modules
        run: |
          docker run --rm update-journals node -v
          docker run --rm update-journals npm list

      - name: Run Docker container
        run: |
          docker run --rm update-journals

      - name: Debug Docker container
        run: |
          docker run --rm update-journals
          echo "Debugging information:"
          docker logs $(docker ps -q -l)
