name: Update Journals Function

on:
  schedule:
    - cron: "0 * * * *"    # تشغيل كل ساعة
  workflow_dispatch:     # للسماح بالتشغيل اليدوي

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t update-journals .

      - name: Run Scraper and Update DB
        # هذه هي الخطوة المعدلة
        # 1. نجعل السر متاحًا كمتغير بيئة
        # 2. نمرر متغير البيئة إلى حاوية دوكر باستخدام -e
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: docker run -e FIREBASE_SERVICE_ACCOUNT_KEY --rm update-journals
